### ISSUE TITLE
question about data preparation

### ISSUE THREAD

**Issue by DHuiTnut** [megvii-research/CVPR2023-UniDistill#1]
Hi, I want to reproduce your code. Can you please tell me that you use the mini version of the dataset or all the data?
![image](https://github.com/megvii-research/CVPR2023-UniDistill/assets/43811941/e5bd7ef8-92f8-410e-b811-4f409d938d57)

**Comment by sczhou21** [comment]
Hello, thanks for your interest. We use the full version of data to conduct our experiments.
