### ISSUE TITLE
代码位置？

### ISSUE THREAD

**Issue by xiaoxusanheyi** [megvii-research/CVPR2023-UniDistill#6]
你好，作者：
     感谢你出色的工作，对此文章的关系蒸馏和响应蒸馏这两部分的代码很感兴趣，是否可以指出它们开始到结束的代码的具体位置所在？

**Comment by sczhou21** [comment]
您好，感谢您对本工作的关注。关系蒸馏和响应蒸馏的代码可以参考unidistill/exps/multisensor_fusion/nuscenes/BEVFusion
/BEVFusion_nuscenes_centerhead_camera_exp_distill_fusion.py文件中的第247行至第384行。

**Comment by xiaoxusanheyi** [comment]
感谢作者！祝好！
